# Word2Vec: interpretação da linguagem humana com Word embedding

In [1]:
import pandas as pd
import tarfile
import os

## Importando dados

In [2]:
with tarfile.open('/home/franciscofoz/Documents/GitHub/machine-learning-training/Processamento de linguagem natural/Datasets/w2v_treino.tar.xz',
                  'r:xz') as tar:
    tar.extractall(path='/home/franciscofoz/Documents/GitHub/machine-learning-training/Processamento de linguagem natural/Datasets')


df_treino = pd.read_csv('/home/franciscofoz/Documents/GitHub/machine-learning-training/Processamento de linguagem natural/Datasets/w2v_treino.csv')



os.remove('/home/franciscofoz/Documents/GitHub/machine-learning-training/Processamento de linguagem natural/Datasets/w2v_treino.csv')

In [3]:
df_teste = pd.read_csv('/home/franciscofoz/Documents/GitHub/machine-learning-training/Processamento de linguagem natural/Datasets/w2v_teste.csv')

In [4]:
df_treino

title  \
0      Após polêmica, Marine Le Pen diz que abomina n...   
1      Macron e Le Pen vão ao 2º turno na França, em ...   
2      Apesar de larga vitória nas legislativas, Macr...   
3      Governo antecipa balanço, e Alckmin anuncia qu...   
4      Após queda em maio, a atividade econômica sobe...   
...                                                  ...   
89995  Mural: Há 30 anos, aeroporto não foi bem receb...   
89996  As notícias sobre Schumacher não são boas, diz...   
89997  De olho em R$ 50 bilhões, governo pode concede...   
89998              Moro deu a Lula o papel de coitadinho   
89999  Velocidade da aprovação das reformas tem 'exce...   

                                                    text        date  \
0      A candidata da direita nacionalista à Presidên...  2017-04-28   
1      O centrista independente Emmanuel Macron e a d...  2017-04-23   
2      As eleições legislativas deste domingo (19) na...  2017-06-19   
3      O número de ocorrências de homicídios dolosos ...  2015-07-24   
4      A economia cresceu 0,25% no segundo trimestre,...  2017-08-17   
...                                                  ...         ...   
89995  Década de 1970. Congonhas já estava superlotad...  2015-01-22   
89996  O ex-presidente da Ferrari Luca di Montezemolo...  2016-04-02   
89997  Para fazer caixa, o governo estuda conceder pa...  2017-08-29   
89998  Realizou-se parcialmente o primeiro objetivo d...  2016-06-03   
89999  O Banco Central afirmou que a velocidade da ap...  2016-10-25   

        category  subcategory  \
0          mundo          NaN   
1          mundo          NaN   
2          mundo          NaN   
3      cotidiano          NaN   
4        mercado          NaN   
...          ...          ...   
89995  cotidiano          NaN   
89996    esporte          NaN   
89997    mercado          NaN   
89998    colunas  eliogaspari   
89999    mercado          NaN   

                                                    link  
0      http://www1.folha.uol.com.br/mundo/2017/04/187...  
1      http://www1.folha.uol.com.br/mundo/2017/04/187...  
2      http://www1.folha.uol.com.br/mundo/2017/06/189...  
3      http://www1.folha.uol.com.br/cotidiano/2015/07...  
4      http://www1.folha.uol.com.br/mercado/2017/08/1...  
...                                                  ...  
89995  http://www1.folha.uol.com.br/cotidiano/2015/01...  
89996  http://www1.folha.uol.com.br/esporte/2016/02/1...  
89997  http://www1.folha.uol.com.br/mercado/2017/08/1...  
89998  http://www1.folha.uol.com.br/colunas/eliogaspa...  
89999  http://www1.folha.uol.com.br/mercado/2016/10/1...  

[90000 rows x 6 columns]

## Exemplo inicial

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html#sklearn.feature_extraction.text.CountVectorizer

In [6]:
texto = ['tenha um bom dia',
         'tenha um ótimo dia',
         'tenha um péssimo dia']

In [7]:
vetorizador = CountVectorizer()
vetorizador.fit(texto)

CountVectorizer()

In [8]:
vetorizador.vocabulary_

{'tenha': 3, 'um': 4, 'bom': 0, 'dia': 1, 'ótimo': 5, 'péssimo': 2}

In [9]:
X = vetorizador.fit_transform(texto)
print(X.toarray())

[[1 1 0 1 1 0]
 [0 1 0 1 1 1]
 [0 1 1 1 1 0]]


## Word2Vec

In [10]:
with open('../Processamento de linguagem natural/Datasets/cbow_s300.txt') as f:
    for linha in range(1000):
        print(next(f))

929606 300

</s> -0.001667 -0.000158 -0.000026 0.001300 -0.000796 0.001527 0.000046 0.000584 0.000449 -0.000100 0.000353 0.001251 0.001069 0.000506 0.000574 0.000838 -0.000930 -0.001220 0.000317 0.001315 -0.001120 0.001373 -0.000040 -0.001580 0.000421 -0.000667 -0.001556 -0.000746 0.001604 0.001157 -0.000027 0.000354 0.000358 -0.000527 -0.000573 -0.001512 -0.001557 -0.001637 0.001617 -0.001511 -0.001022 -0.001426 0.001086 -0.001033 0.000593 0.000724 0.000627 -0.000450 -0.001140 0.000333 0.000524 0.001541 0.000284 0.000617 -0.000807 -0.000088 -0.000364 0.001126 -0.001230 -0.001138 -0.001280 0.001330 0.001257 0.000576 0.000764 0.000684 0.001008 -0.000215 -0.000629 -0.001228 -0.001557 -0.000311 -0.000246 0.000045 0.001136 -0.000645 -0.000549 0.001099 0.000858 -0.000886 0.000553 0.000303 0.001433 0.000732 0.001321 -0.000894 -0.000700 -0.000661 -0.001484 -0.000950 -0.001556 -0.000809 0.000348 -0.000068 0.000724 -0.000569 -0.000161 -0.001628 -0.001437 -0.000259 -0.000296 -0.001571 0.000149 0

In [11]:
from gensim.models import KeyedVectors

In [12]:
modelo = KeyedVectors.load_word2vec_format('../Processamento de linguagem natural/Datasets/cbow_s300.txt')

In [13]:
modelo.most_similar('bom')

[('mau', 0.682968258857727),
 ('ótimo', 0.6798622608184814),
 ('péssimo', 0.6452513337135315),
 ('óptimo', 0.5934253931045532),
 ('pã©ssimo', 0.5159831047058105),
 ('ruim', 0.5159329771995544),
 ('satisfatório', 0.51152503490448),
 ('perfeito', 0.49735376238822937),
 ('maravilhoso', 0.47296249866485596),
 ('insatisfatório', 0.4607459008693695)]

In [14]:
modelo.most_similar('alemanha')

[('bélgica', 0.7396209239959717),
 ('ale-manha', 0.7230488061904907),
 ('itália', 0.7135661244392395),
 ('finlândia', 0.7134818434715271),
 ('frança', 0.6954975128173828),
 ('áustria', 0.6904557943344116),
 ('dinamarca', 0.6875618696212769),
 ('suécia', 0.6848708391189575),
 ('holanda', 0.6763718724250793),
 ('rússia', 0.6680961847305298)]

In [15]:
modelo.most_similar('alemanha')

[('bélgica', 0.7396209239959717),
 ('ale-manha', 0.7230488061904907),
 ('itália', 0.7135661244392395),
 ('finlândia', 0.7134818434715271),
 ('frança', 0.6954975128173828),
 ('áustria', 0.6904557943344116),
 ('dinamarca', 0.6875618696212769),
 ('suécia', 0.6848708391189575),
 ('holanda', 0.6763718724250793),
 ('rússia', 0.6680961847305298)]

In [16]:
modelo.most_similar(positive=['japão','china'])

[('canadá', 0.6659026741981506),
 ('índia', 0.6308273077011108),
 ('tailândia', 0.6230262517929077),
 ('rússia', 0.617530345916748),
 ('austrália', 0.6162929534912109),
 ('malásia', 0.6063832640647888),
 ('camboja', 0.6031984686851501),
 ('vietname', 0.5979725122451782),
 ('indonésia', 0.5926010012626648),
 ('taiwan', 0.5843464136123657)]

In [17]:
modelo.most_similar(positive=['nuvens','estrela'],negative=['nuvem'])

[('estrelas', 0.5497430562973022),
 ('plêiades', 0.379197895526886),
 ('colinas', 0.3746805489063263),
 ('trovoadas', 0.3737032413482666),
 ('sombras', 0.3734194040298462),
 ('pombas', 0.3726757764816284),
 ('corredoras', 0.3640727400779724),
 ('cigarras', 0.36065393686294556),
 ('galáxias', 0.35754910111427307),
 ('luas', 0.3575345277786255)]

In [18]:
modelo.most_similar(positive=['médico','mulher'],negative=['homem'])

[('enfermeira', 0.6180862188339233),
 ('psicóloga', 0.47447526454925537),
 ('dama-de-companhia', 0.47382351756095886),
 ('esposa', 0.46559134125709534),
 ('parteira', 0.46362870931625366),
 ('mãe', 0.45817673206329346),
 ('governanta', 0.45722928643226624),
 ('madrasta', 0.4569782614707947),
 ('menina', 0.4443591237068176),
 ('filha', 0.44341108202934265)]

In [19]:
modelo.most_similar(positive=['professor','mulher'],negative=['homem'])

[('professora', 0.6192208528518677),
 ('aluna', 0.5449554324150085),
 ('esposa', 0.4978231191635132),
 ('ex-aluna', 0.4884248375892639),
 ('namorada', 0.4737858474254608),
 ('enfermeira', 0.4728143513202667),
 ('filha', 0.4673738479614258),
 ('irmã', 0.45845916867256165),
 ('ex-namorada', 0.45824769139289856),
 ('ex-professora', 0.45104706287384033)]

## Vetorização de texto

In [20]:
df_treino.title.loc[12]

"Daniel Craig será stormtrooper em novo 'Star Wars', diz ator"

In [21]:
import nltk
import string

def tokenizador(texto):
    
    texto = texto.lower()
    
    lista_alfanumerico = list()
    
    for token_valido in nltk.word_tokenize(texto):
        if token_valido in string.punctuation: continue  
        lista_alfanumerico.append(token_valido)
    
    return lista_alfanumerico


tokenizador('texto Exemplo, 1234')

['texto', 'exemplo', '1234']

In [22]:
tokenizador(df_treino.title.loc[13])

['justiça',
 'de',
 'sp',
 'libera',
 'construção',
 'de',
 'moradias',
 'em',
 'manancial',
 'da',
 'billings']

In [23]:
import numpy as np

In [24]:
def combinacao_de_vetores_por_soma(palavras_numeros):
    
    vetor_resultante = np.zeros(300)
    
    for pn in palavras_numeros:
        
        try:
            vetor_resultante += modelo.get_vector(pn)
        except KeyError:
            if pn.isnumeric():
                pn = '0'*len(pn)
                vetor_resultante += modelo.get_vector(pn)
            else:
                vetor_resultante += modelo.get_vector('unknown')
                
    return vetor_resultante
    
    

In [25]:
palavras_numeros = tokenizador(df_treino.title.loc[13])
palavras_numeros

['justiça',
 'de',
 'sp',
 'libera',
 'construção',
 'de',
 'moradias',
 'em',
 'manancial',
 'da',
 'billings']

In [26]:
combinacao_de_vetores_por_soma(palavras_numeros)

array([-1.11027099,  0.384391  , -0.68784401, -1.60555302,  1.13189701,
       -1.411592  ,  0.54454799, -0.751419  ,  0.562526  ,  0.35972501,
        0.392724  ,  1.00472503,  0.45130202, -0.086302  , -0.467375  ,
        0.78460801, -0.54604402,  0.08133201, -1.03974602,  0.88660002,
       -0.603356  , -0.43857701, -0.300273  ,  0.40063803,  0.46923901,
       -0.88572298,  1.101129  , -0.30328098,  1.00781198, -0.14397899,
        0.849722  , -0.705847  ,  0.183487  ,  0.59475101, -0.612876  ,
        0.34887   , -0.00344   , -0.80568502,  0.01239301, -0.32647898,
       -0.59522202, -0.323529  , -0.81964197,  0.06720101, -0.927902  ,
        0.55038898,  1.131301  , -0.92626   , -0.04648296, -0.41346901,
        0.569285  ,  0.13160199, -0.295014  ,  0.486882  , -0.789929  ,
       -0.67429001, -0.79323502, -0.20330002, -0.79219101,  0.363218  ,
       -0.50363499,  0.47120202,  0.88150299,  0.63021301, -0.880954  ,
        1.55131399,  0.10461097, -0.44017501, -1.03467102,  0.33

In [27]:
palavras_numeros = tokenizador(df_treino.title.loc[12])
combinacao_de_vetores_por_soma(palavras_numeros)

array([ 1.67317901, -0.20292199, -0.22226603, -0.11928599,  0.26908902,
        0.08942802,  0.12082599, -0.23207501,  0.18146399, -0.730078  ,
       -1.21077401, -0.03985799,  0.32729501,  0.94589301, -1.45712802,
        0.395658  , -1.43962501, -0.155651  , -1.585321  , -0.31727697,
       -2.15443001, -1.16325702, -0.67953501,  1.09901099,  0.343745  ,
        0.134513  , -0.92588304,  0.32897799,  0.99758601,  0.40186502,
        0.94387899, -0.23940401,  0.47804301,  0.72704102, -0.66623902,
        0.165928  ,  0.852507  , -0.36187701, -0.71582198,  0.47276502,
       -1.18974499,  0.44784799,  1.052032  ,  0.37330001,  0.36469799,
        1.02378795,  0.29186101, -0.42506199,  1.510164  , -0.30298898,
        0.03237198, -0.36912799,  1.07161801,  0.650188  , -0.37763803,
       -0.40839299,  0.06470999,  0.68308198,  0.10497496,  0.230406  ,
       -0.73960799,  0.17970599,  0.64611303,  0.08515099, -0.50041199,
        0.379802  ,  0.97226496,  0.59061098, -0.284091  , -0.49

In [51]:
def matriz_vetores(textos):
    x = len(textos)
    y = 300
    
    matriz = np.zeros((x,y))
    
    for i in range(x):
        palavras_numeros = tokenizador(textos.iloc[i])
        matriz[i] = combinacao_de_vetores_por_soma(palavras_numeros)
        
    return matriz


In [52]:
matriz_vetores(df_treino.head(1000).title)

array([[ 0.52357099,  1.00529201,  0.26381801, ...,  0.43726099,
         0.187696  ,  0.15216099],
       [ 0.34492697,  0.83511301, -0.88874401, ...,  0.19878698,
        -1.40402502,  1.49788603],
       [ 0.050757  ,  0.95369402,  0.63757797, ...,  0.252318  ,
         0.142377  , -1.36338596],
       ...,
       [-0.00711698,  0.597002  , -0.25209202, ..., -0.22790999,
        -0.733866  , -0.29938398],
       [-0.093454  ,  0.36938801,  0.63799999, ...,  0.88337499,
        -1.07795703, -1.034894  ],
       [-0.49440101, -0.66821902, -0.76292601, ...,  0.01182202,
         0.15708297, -0.30152898]])

In [59]:
matriz_vetores_treino = matriz_vetores(df_treino.title)


In [60]:
matriz_vetores_teste = matriz_vetores(df_teste.title)

## Classificando os textos

In [61]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(max_iter=200)


In [62]:
LR.fit(matriz_vetores_treino,df_treino.category)

LogisticRegression(max_iter=200)

In [63]:
LR.n_iter_

array([118], dtype=int32)

In [66]:
LR.score(matriz_vetores_teste,df_teste.category)

0.7957880368546775

In [68]:
df_teste.category.unique()

array(['colunas', 'esporte', 'mercado', 'cotidiano', 'mundo', 'ilustrada'],
      dtype=object)

In [71]:
from sklearn.metrics import classification_report

label_prevista = LR.predict(matriz_vetores_teste)
CR = classification_report(df_teste.category,label_prevista)
print(CR)

              precision    recall  f1-score   support

     colunas       0.86      0.71      0.78      6103
   cotidiano       0.61      0.79      0.69      1698
     esporte       0.92      0.88      0.90      4663
   ilustrada       0.13      0.88      0.23       131
     mercado       0.84      0.79      0.81      5867
       mundo       0.74      0.86      0.79      2051

    accuracy                           0.80     20513
   macro avg       0.68      0.82      0.70     20513
weighted avg       0.83      0.80      0.81     20513



In [74]:
from sklearn.dummy import DummyClassifier

DC = DummyClassifier()
DC.fit(matriz_vetores_treino,df_treino.category)

label_prevista_dc = DC.predict(matriz_vetores_teste)
DC = classification_report(df_teste.category,label_prevista_dc)
print(DC)

/home/franciscofoz/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/franciscofoz/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

     colunas       0.30      1.00      0.46      6103
   cotidiano       0.00      0.00      0.00      1698
     esporte       0.00      0.00      0.00      4663
   ilustrada       0.00      0.00      0.00       131
     mercado       0.00      0.00      0.00      5867
       mundo       0.00      0.00      0.00      2051

    accuracy                           0.30     20513
   macro avg       0.05      0.17      0.08     20513
weighted avg       0.09      0.30      0.14     20513



/home/franciscofoz/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
